// frontend/src/app/dashboard/coach/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";
import { supabase } from "@/lib/supabase";
import apiClient from "@/lib/apiClient";
import {
  Zap,
  Sparkles,
  Target,
  RefreshCw,
  CheckCircle2,
  ShieldAlert,
  Trophy,
  Flame,
  Mountain,
  Timer,
  Activity,
  User,
  Heart
} from "lucide-react";

export default function CoachPage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<any>(null);
  const [targetRace, setTargetRace] = useState("武功山 50K");
  const [targetTime, setTargetTime] = useState("8:00:00");
  const [raceType, setRaceType] = useState("trail");

  const racePresets = [
    { label: "🏔️ 武功山 50K (越野)", race: "武功山 50K", time: "8:00:00", type: "trail" },
    { label: "🏅 无锡马拉松 (全马)", race: "无锡马拉松", time: "3:15:00", type: "marathon" },
    { label: "⚡ 上海半马 (半马)", race: "上海半程马拉松", time: "1:35:00", type: "half" },
    { label: "🏃 10K 速度突破", race: "日常 10公里 突破", time: "42:00", type: "10k" },
  ];

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      const u = data?.session?.user;
      if (u) {
        setUser(u);
        loadLatestAnalysis(u.id);
      } else {
        router.push("/login");
      }
    });
  }, [router]);

  async function loadLatestAnalysis(uid: string) {
    try {
      const res = await apiClient.get(`/api/coach/latest/${uid}`);
      if (res.data && res.data.summary) {
        setAnalysis(res.data);
        if (res.data.athlete_snapshot?.target_race) {
          setTargetRace(res.data.athlete_snapshot.target_race);
        }
        if (res.data.athlete_snapshot?.target_time) {
          setTargetTime(res.data.athlete_snapshot.target_time);
        }
        if (res.data.athlete_snapshot?.race_category) {
          setRaceType(res.data.athlete_snapshot.race_category);
        }
      }
    } catch (e) {
      console.error("Latest coach report fetch error:", e);
    }
  }

  async function handleGenerateAnalysis() {
    if (!user?.id) return;
    setLoading(true);
    try {
      const res = await apiClient.post("/api/coach/analysis", {
        uid: user.id,
        target_race: targetRace,
        target_time: targetTime,
        race_type: raceType,
      });
      if (res.data) {
        setAnalysis(res.data);
      }
    } catch (e) {
      console.error("Coach generation failed:", e);
      alert("AI 分析生成提示: 正在使用最近一次训练诊断缓存");
    } finally {
      setLoading(false);
    }
  }

  const tsb = analysis?.tsb_metrics?.tsb ?? 0;
  const ctl = analysis?.tsb_metrics?.ctl ?? 0;
  const atl = analysis?.tsb_metrics?.atl ?? 0;
  const statusLabel = analysis?.tsb_metrics?.status ?? "平衡稳健";
  const riskWarning = analysis?.tsb_metrics?.risk_warning;
  const athlete = analysis?.athlete_snapshot;
  const zones = analysis?.race_zones;

  const getTsbColor = (val: number) => {
    if (val > 15) return "text-emerald-400 border-emerald-500/30 bg-emerald-500/10";
    if (val >= -10) return "text-cyan-400 border-cyan-500/30 bg-cyan-500/10";
    if (val >= -30) return "text-purple-400 border-purple-500/30 bg-purple-500/10";
    if (val >= -45) return "text-amber-400 border-amber-500/30 bg-amber-500/10";
    return "text-red-400 border-red-500/30 bg-red-500/10";
  };


  return (
    <div className="min-h-screen bg-[#070708] text-white">
      <Navbar />

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8 space-y-8">
        {/* Title Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-black flex items-center gap-2.5">
              <Zap className="w-7 h-7 text-purple-400" />
              Renato Canova AI 智能耐力教练
            </h1>
            <p className="text-xs sm:text-sm text-zinc-400 mt-1">
              世界级专项化训练哲学 · 5K/半马/全马/越野因赛制宜 · 动态 TSB 负荷与年龄自适应
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleGenerateAnalysis}
              disabled={loading}
              className="flex items-center gap-2 px-5 py-2.5 rounded-2xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold transition-all shadow-lg shadow-purple-600/25 active:scale-95 disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              {loading ? "AI 深度推理中..." : "启动 AI 专项推理"}
            </button>
          </div>
        </div>

        {/* Top Control Bar: Athlete Profile & Race Setup */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Athlete Profile & Physiological Form */}
          <div className="bg-[#121215] border border-white/[0.08] rounded-3xl p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-zinc-400 flex items-center gap-1.5">
                <User className="w-3.5 h-3.5 text-purple-400" /> 跑者生理档案
              </span>
              <span className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full border ${getTsbColor(tsb)}`}>
                {statusLabel}
              </span>
            </div>

            <div className="space-y-2">
              <div className="text-lg font-black text-white">
                {athlete?.name || "跑者"}
                <span className="ml-2 text-xs font-medium text-zinc-400">
                  {athlete?.gender === "female" ? "♀ 女性" : "♂ 男性"}
                </span>
              </div>
              <div className="text-xs text-zinc-400 flex items-center gap-3">
                <span>周岁: <strong className="text-purple-300">{athlete?.age ? `${athlete.age} 岁` : "未登记"}</strong></span>
                <span>跑龄: <strong className="text-purple-300">{athlete?.years_running || 2} 年</strong></span>
              </div>
            </div>

            {/* TSB Metric Indicators */}
            <div className="grid grid-cols-3 gap-2 pt-2 border-t border-white/5">
              <div className="bg-[#18181c] p-2.5 rounded-xl text-center">
                <div className="text-[10px] text-zinc-400">体能 CTL</div>
                <div className="text-sm font-black text-cyan-400 mt-0.5">{ctl}</div>
              </div>
              <div className="bg-[#18181c] p-2.5 rounded-xl text-center">
                <div className="text-[10px] text-zinc-400">疲劳 ATL</div>
                <div className="text-sm font-black text-amber-400 mt-0.5">{atl}</div>
              </div>
              <div className="bg-[#18181c] p-2.5 rounded-xl text-center">
                <div className="text-[10px] text-zinc-400">状态 TSB</div>
                <div className={`text-sm font-black mt-0.5 ${tsb >= 0 ? "text-emerald-400" : "text-purple-400"}`}>
                  {tsb > 0 ? `+${tsb}` : tsb}
                </div>
              </div>
            </div>

            {riskWarning && (
              <div className="p-3 bg-red-950/40 border border-red-500/30 rounded-2xl flex items-start gap-2 text-xs text-red-200">
                <ShieldAlert className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
                <span className="leading-snug">{riskWarning}</span>
              </div>
            )}
          </div>

          {/* Interactive Target Race & Type Customization */}
          <div className="lg:col-span-2 bg-[#121215] border border-white/[0.08] rounded-3xl p-6 shadow-xl space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-purple-400 flex items-center gap-1.5">
                <Target className="w-3.5 h-3.5" /> 目标赛事与专项类型设定
              </span>
              <span className="text-xs text-zinc-500">
                Canova 哲学核心：专项性依赛事而变
              </span>
            </div>

            {/* Quick Presets */}
            <div className="flex flex-wrap gap-2">
              {racePresets.map((p, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setTargetRace(p.race);
                    setTargetTime(p.time);
                    setRaceType(p.type);
                  }}
                  className={`text-xs px-3 py-1.5 rounded-xl border transition-all ${
                    targetRace === p.race
                      ? "bg-purple-600/30 border-purple-500 text-purple-200 font-bold"
                      : "bg-[#18181c] border-white/5 text-zinc-400 hover:text-white"
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
              <div>
                <label className="text-[11px] text-zinc-400 block mb-1">目标赛事名称</label>
                <input
                  type="text"
                  value={targetRace}
                  onChange={(e) => setTargetRace(e.target.value)}
                  placeholder="例如: 武功山 50K / 无锡马拉松"
                  className="w-full bg-[#18181c] border border-white/10 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="text-[11px] text-zinc-400 block mb-1">专项赛事类型</label>
                <select
                  value={raceType}
                  onChange={(e) => setRaceType(e.target.value)}
                  className="w-full bg-[#18181c] border border-white/10 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-purple-500"
                >
                  <option value="trail">越野超马 (山地爬升 D+ / 时间负荷)</option>
                  <option value="marathon">全程马拉松 (100% MP 配速收敛)</option>
                  <option value="half">半程马拉松 (LT2 乳酸门槛巡航)</option>
                  <option value="10k">10公里场地/路跑 (VO2max 峰值刺激)</option>
                  <option value="5k">5公里竞速 (乳酸耐受极限)</option>
                </select>
              </div>

              <div>
                <label className="text-[11px] text-zinc-400 block mb-1">目标完赛成绩 (HH:MM:SS)</label>
                <input
                  type="text"
                  value={targetTime}
                  onChange={(e) => setTargetTime(e.target.value)}
                  placeholder="例如: 8:00:00 或 3:15:00"
                  className="w-full bg-[#18181c] border border-white/10 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-purple-500"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Coach Analysis Result Display */}
        {analysis ? (
          <div className="space-y-6">
            {/* Summary Hero Card */}
            <div className="bg-gradient-to-br from-purple-900/30 via-[#121215] to-[#16161a] border border-purple-500/30 rounded-3xl p-6 sm:p-8 shadow-2xl">
              <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-purple-500/20 text-purple-300 text-xs font-bold mb-4 border border-purple-500/30">
                <Sparkles className="w-3.5 h-3.5" />
                当前训练阶段：{analysis.periodization_phase || "专项准备期"}
              </div>
              <h2 className="text-xl sm:text-2xl font-black text-white mb-3">
                {analysis.summary}
              </h2>
              <p className="text-sm text-zinc-300 leading-relaxed font-light">
                {analysis.fitness_status}
              </p>
            </div>

            {/* Specificity Training Zones (Canova Zones for Target Race) */}
            {zones && (
              <div className="bg-[#121215] border border-white/[0.08] rounded-3xl p-6 sm:p-8 shadow-2xl">
                <h3 className="text-sm font-bold uppercase tracking-wider text-purple-400 mb-4 flex items-center gap-2">
                  <Activity className="w-4 h-4" /> Canova 比赛专项刺激区间参考 ({targetRace})
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3">
                  {Object.entries(zones).map(([k, z]: [string, any]) => (
                    <div key={k} className="bg-[#18181c] border border-white/5 p-3.5 rounded-2xl flex flex-col justify-between">
                      <div>
                        <div className="text-[11px] font-bold text-zinc-400 mb-1">{z.name}</div>
                        <div className="text-sm font-black text-purple-300 tracking-tight">{z.range}</div>
                      </div>
                      <div className="text-[10px] text-zinc-500 mt-2 leading-tight">{z.desc}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Key Suggestions & Focus Workout */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Focus Workout */}
              <div className="bg-[#121215] border border-white/[0.08] rounded-3xl p-6 sm:p-8 shadow-2xl flex flex-col justify-between">
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-purple-400 mb-4 flex items-center gap-2">
                    <Target className="w-4 h-4" /> 本周核心专项关键课
                  </h3>
                  <div className="p-4 bg-purple-950/20 border border-purple-500/20 rounded-2xl text-sm font-medium text-purple-100 leading-relaxed whitespace-pre-line">
                    {typeof analysis.focus_workout_of_the_week === "object" && analysis.focus_workout_of_the_week
                      ? Object.entries(analysis.focus_workout_of_the_week).map(([k, v]) => `【${k}】${v}`).join("\n")
                      : String(analysis.focus_workout_of_the_week || "热身 3km + 3 × 4000m @ 专项配速 + 2km 冷身")}
                  </div>
                </div>
                <p className="text-xs text-zinc-500 mt-4">
                  * 建议在充分热身与休息充沛状态下执行此课表。
                </p>
              </div>

              {/* Recovery Advice */}
              <div className="bg-[#121215] border border-white/[0.08] rounded-3xl p-6 sm:p-8 shadow-2xl flex flex-col justify-between">
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-400 mb-4 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4" /> 生理恢复与超量恢复指导
                  </h3>
                  <div className="p-4 bg-emerald-950/20 border border-emerald-500/20 rounded-2xl text-sm font-medium text-emerald-100 leading-relaxed">
                    {analysis.recovery_advice}
                  </div>
                </div>
                <p className="text-xs text-zinc-500 mt-4">
                  * 密切关注晨起静息心率与睡眠质量得分。
                </p>
              </div>
            </div>

            {/* Detailed Key Suggestions List */}
            <div className="bg-[#121215] border border-white/[0.08] rounded-3xl p-6 sm:p-8 shadow-2xl">
              <h3 className="text-base font-bold text-white mb-4 flex items-center gap-2">
                <span>🎯</span> Canova 专项训练执行要点
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {(analysis.key_suggestions || []).map((sugg: string, idx: number) => (
                  <div key={idx} className="bg-[#18181c] border border-white/5 p-4 rounded-2xl">
                    <span className="text-xs font-bold text-purple-400 block mb-1.5">
                      重点 0{idx + 1}
                    </span>
                    <p className="text-xs text-zinc-300 leading-relaxed">{sugg}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-20 bg-[#121215] border border-white/[0.08] rounded-3xl p-8 shadow-2xl">
            <div className="w-16 h-16 rounded-3xl bg-purple-500/10 text-purple-400 flex items-center justify-center mx-auto mb-4">
              <Zap className="w-8 h-8" />
            </div>
            <h3 className="text-lg font-bold text-white mb-2">Canova AI 教练就绪</h3>
            <p className="text-xs text-zinc-400 max-w-sm mx-auto mb-6">
              配置您的目标赛事，点击上方“启动 AI 专项推理”，AI 教练将基于您的近期 Garmin / 高驰训练与生理负荷生成专属报告。
            </p>
            <button
              onClick={handleGenerateAnalysis}
              disabled={loading}
              className="px-6 py-3 rounded-2xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold transition shadow-lg shadow-purple-600/30"
            >
              生成最新训练诊断
            </button>
          </div>
        )}
      </main>
    </div>
  );
}

// miniapp/src/pages/coach/coach.vue
<template>
  <view class="coach-page">
    <!-- Header -->
    <view class="coach-header">
      <view class="header-left">
        <view class="title-row">
          <text class="title-icon">⚡</text>
          <text class="page-title">Canova AI 智能耐力教练</text>
        </view>
        <text class="page-subtitle">世界级专项化哲学 · 5K/半马/全马/越野因赛制宜 · 动态 TSB 与年龄自适应</text>
      </view>

      <button class="re-analyze-btn" :loading="loading" :disabled="loading" @click="handleReAnalyze">
        <text class="btn-text">{{ loading ? "AI 推理中..." : "启动专项推理" }}</text>
      </button>
    </view>

    <!-- ── ATHLETE PROFILE & TSB FORM CARD ── -->
    <view class="profile-card">
      <view class="profile-top">
        <view class="profile-name-box">
          <text class="profile-name">{{ athleteInfo.name || "跑者" }}</text>
          <text class="profile-meta">
            {{ athleteInfo.gender === 'female' ? '♀ 女' : '♂ 男' }} · 
            {{ athleteInfo.age ? `${athleteInfo.age} 岁` : '未录入年龄' }} · 
            跑龄 {{ athleteInfo.years_running || 2 }} 年
          </text>
        </view>
        <view class="tsb-badge" :class="tsbClass">
          <text class="tsb-badge-text">{{ tsbMetrics.status || "平衡稳健" }}</text>
        </view>
      </view>

      <view class="tsb-grid">
        <view class="tsb-item">
          <text class="tsb-label">体能 CTL</text>
          <text class="tsb-val text-cyan">{{ tsbMetrics.ctl || 0 }}</text>
        </view>
        <view class="tsb-item">
          <text class="tsb-label">疲劳 ATL</text>
          <text class="tsb-val text-amber">{{ tsbMetrics.atl || 0 }}</text>
        </view>
        <view class="tsb-item">
          <text class="tsb-label">状态 TSB</text>
          <text class="tsb-val" :class="tsbMetrics.tsb >= 0 ? 'text-green' : 'text-purple'">
            {{ tsbMetrics.tsb > 0 ? `+${tsbMetrics.tsb}` : (tsbMetrics.tsb || 0) }}
          </text>
        </view>
      </view>

      <view v-if="tsbMetrics.risk_warning" class="risk-box">
        <text class="risk-icon">⚠️</text>
        <text class="risk-text">{{ tsbMetrics.risk_warning }}</text>
      </view>
    </view>

    <!-- ── TARGET RACE CUSTOMIZATION CARD ── -->
    <view class="race-setup-card">
      <view class="card-title-row">
        <text class="section-icon">🎯</text>
        <text class="card-title">目标赛事与专项设定</text>
      </view>

      <!-- Preset Chips -->
      <view class="presets-row">
        <view
          v-for="(p, idx) in racePresets"
          :key="idx"
          class="preset-chip"
          :class="{ active: targetRace === p.race }"
          @click="applyPreset(p)"
        >
          <text class="chip-text">{{ p.label }}</text>
        </view>
      </view>

      <view class="inputs-row">
        <view class="input-col flex-2">
          <text class="input-label">目标赛事</text>
          <input
            v-model="targetRace"
            placeholder="如: 武功山 50K"
            class="setup-input"
          />
        </view>
        <view class="input-col flex-1">
          <text class="input-label">目标时间</text>
          <input
            v-model="targetTime"
            placeholder="8:00:00"
            class="setup-input"
          />
        </view>
      </view>
    </view>

    <!-- Main Content -->
    <view v-if="analysis" class="content-box">
      <!-- ── CARD 1: 当前阶段与核心评价 ── -->
      <view class="hero-card">
        <view class="phase-badge">
          <text class="sparkle">✨</text>
          <text class="phase-text">当前阶段：{{ analysis.periodization_phase || "专项准备期 (Special Period)" }}</text>
        </view>

        <text class="summary-title">{{ analysis.summary }}</text>
        <text class="fitness-detail">{{ analysis.fitness_status }}</text>
      </view>

      <!-- ── CARD 1.5: CANOVA 比赛专项刺激区间 ── -->
      <view v-if="analysis.race_zones" class="section-card">
        <view class="card-title-row">
          <text class="section-icon">⚡</text>
          <text class="card-title">Canova 比赛专项刺激区间 ({{ targetRace }})</text>
        </view>

        <view class="zones-list">
          <view
            v-for="(z, key) in analysis.race_zones"
            :key="key"
            class="zone-item"
          >
            <view class="zone-header">
              <text class="zone-name">{{ z.name }}</text>
              <text class="zone-range">{{ z.range }}</text>
            </view>
            <text class="zone-desc">{{ z.desc }}</text>
          </view>
        </view>
      </view>

      <!-- ── CARD 2: 本周核心关键课 ── -->
      <view class="section-card workout-card">
        <view class="card-title-row">
          <text class="section-icon">🎯</text>
          <text class="card-title">本周核心专项关键课</text>
        </view>
        <view class="workout-box">
          <text class="workout-text">{{ formatWorkout(analysis.focus_workout_of_the_week) }}</text>
        </view>
        <text class="tip-footnote">* 建议在充分热身与休息充沛状态下执行此课表。</text>
      </view>

      <!-- ── CARD 3: 生理恢复与超量恢复指导 ── -->
      <view class="section-card recovery-card">
        <view class="card-title-row">
          <text class="section-icon">🌿</text>
          <text class="card-title">生理恢复与超量恢复指导</text>
        </view>
        <view class="recovery-box">
          <text class="recovery-text">{{ analysis.recovery_advice }}</text>
        </view>
        <text class="tip-footnote">* 密切关注晨起静息心率与睡眠质量得分。</text>
      </view>

      <!-- ── CARD 4: Canova 专项训练执行要点 ── -->
      <view class="section-card">
        <view class="card-title-row">
          <text class="section-icon">📋</text>
          <text class="card-title">Canova 专项训练执行要点</text>
        </view>

        <view class="suggestions-list">
          <view
            v-for="(item, idx) in (analysis.key_suggestions || [])"
            :key="idx"
            class="sugg-item"
          >
            <text class="sugg-badge">重点 0{{ idx + 1 }}</text>
            <text class="sugg-text">{{ item }}</text>
          </view>
        </view>
      </view>
    </view>

    <!-- Empty / Fallback State -->
    <view v-else class="empty-card">
      <text class="empty-icon">⚡</text>
      <text class="empty-title">Canova AI 教练就绪</text>
      <text class="empty-desc">配置您的目标赛事，点击下方按钮，AI 教练将基于您的近期 Garmin / 高驰训练与生理负荷生成专属报告。</text>
      <button class="primary-btn" :loading="loading" @click="handleReAnalyze">生成最新训练诊断</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { onShow, onPullDownRefresh } from "@dcloudio/uni-app";
import { request, getStoredUser, checkAndAutoLogin, UserProfile } from "../../utils/api";

const racePresets = [
  { label: "🏔️ 武功山 50K", race: "武功山 50K", time: "8:00:00", type: "trail" },
  { label: "🏅 无锡全马", race: "无锡马拉松", time: "3:15:00", type: "marathon" },
  { label: "⚡ 上海半马", race: "上海半程马拉松", time: "1:35:00", type: "half" },
  { label: "🏃 10K 速度", race: "日常 10公里 突破", time: "42:00", type: "10k" },
];

const targetRace = ref("武功山 50K");
const targetTime = ref("8:00:00");
const raceType = ref("trail");

function applyPreset(p: any) {
  targetRace.value = p.race;
  targetTime.value = p.time;
  raceType.value = p.type;
}

const defaultAnalysis = {
  summary: "欢迎来到 Renato Canova AI 耐力教练专区！绑定 Garmin 或高驰手表后将自动生成您的专属报告。",
  fitness_status: "系统将基于您的每日配速、静息心率与夜间 HRV 恢复状态，智能量化评估专项耐力与疲劳水平。",
  periodization_phase: "准备启动期 (Preparation)",
  key_suggestions: [
    "在【我的】页面绑定您的 Garmin 或高驰账号，开启历史运动与每日生理指标同步。",
    "以轻松跑 (Zone 2) 为主积累有氧基线，建立慢肌纤维毛细血管网。",
    "保持科学作息，长跑后注意水分电解质补充与睡眠恢复。"
  ],
  focus_workout_of_the_week: "基础有氧建立：轻松跑 30~45 分钟，心率控制在最大心率的 65%~75% 之间。",
  recovery_advice: "夜间保证 7~8 小时高质量睡眠，观察晨起静息心率变化，建立稳定生理基线。"
};

const user = ref<UserProfile | null>(null);
const analysis = ref<any>(defaultAnalysis);
const loading = ref(false);

const athleteInfo = computed(() => analysis.value?.athlete_snapshot || {});
const tsbMetrics = computed(() => analysis.value?.tsb_metrics || {});

const tsbClass = computed(() => {
  const val = tsbMetrics.value?.tsb ?? 0;
  if (val > 15) return "tsb-fresh";
  if (val >= -10) return "tsb-neutral";
  if (val >= -30) return "tsb-optimal";
  if (val >= -45) return "tsb-fatigued";
  return "tsb-danger";
});

async function loadLatestReport() {
  user.value = getStoredUser();
  if (!user.value) {
    user.value = await checkAndAutoLogin();
  }
  if (!user.value || !user.value.id) return;
  const uid = user.value.id;

  try {
    const res = await request(`/api/coach/latest/${uid}`);
    if (res && res.summary) {
      analysis.value = res;
      if (res.athlete_snapshot?.target_race) {
        targetRace.value = res.athlete_snapshot.target_race;
      }
      if (res.athlete_snapshot?.target_time) {
        targetTime.value = res.athlete_snapshot.target_time;
      }
      if (res.athlete_snapshot?.race_category) {
        raceType.value = res.athlete_snapshot.race_category;
      }
    }
  } catch (e) {
    console.warn("Fetch coach report fallback:", e);
  }
}

async function handleReAnalyze() {
  user.value = getStoredUser();
  if (!user.value) {
    user.value = await checkAndAutoLogin();
  }
  if (!user.value || !user.value.id) return;
  const uid = user.value.id;

  loading.value = true;
  uni.showLoading({ title: "AI 深度推理中..." });

  try {
    const res = await request("/api/coach/analysis", "POST", {
      uid,
      target_race: targetRace.value,
      target_time: targetTime.value,
      race_type: raceType.value
    });
    uni.hideLoading();
    if (res && res.summary) {
      analysis.value = res;
      uni.showToast({ title: "诊断报告已更新", icon: "success" });
    }
  } catch (e) {
    uni.hideLoading();
    uni.showToast({ title: "已加载最新分析", icon: "success" });
  } finally {
    loading.value = false;
  }
}

function formatWorkout(w: any): string {
  if (!w) return "热身 3km + 3 × 4000m @ 专项配速 (间歇 1000m 漂浮跑) + 2km 冷身";
  if (typeof w === "string") return w;
  if (typeof w === "object") {
    return Object.entries(w).map(([k, v]) => `【${k}】${v}`).join("\n");
  }
  return String(w);
}

onShow(() => {
  loadLatestReport();
});

onPullDownRefresh(async () => {
  try {
    await loadLatestReport();
    uni.showToast({ title: "数据已刷新", icon: "success" });
  } catch (e) {
    uni.showToast({ title: "已是最新报告", icon: "none" });
  } finally {
    uni.stopPullDownRefresh();
  }
});

</script>

<style scoped>
.coach-page {
  min-height: 100vh;
  background-color: #0b0b0d;
  padding: 30rpx 30rpx 60rpx 30rpx;
  box-sizing: border-box;
}

.coach-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30rpx;
}

.header-left {
  flex: 1;
  margin-right: 20rpx;
}

.title-row {
  display: flex;
  align-items: center;
  gap: 12rpx;
}

.title-icon {
  font-size: 36rpx;
  color: #bf5af2;
}

.page-title {
  font-size: 34rpx;
  font-weight: 900;
  color: #ffffff;
}

.page-subtitle {
  font-size: 22rpx;
  color: #8e8e93;
  margin-top: 6rpx;
  display: block;
}

.re-analyze-btn {
  background: linear-gradient(135deg, #af52de 0%, #8e44ad 100%);
  color: #ffffff;
  font-size: 24rpx;
  font-weight: bold;
  padding: 0 24rpx;
  height: 64rpx;
  line-height: 64rpx;
  border-radius: 32rpx;
  border: none;
  box-shadow: 0 6rpx 16rpx rgba(175, 82, 222, 0.3);
}

.btn-text {
  font-size: 24rpx;
}

.content-box {
  display: flex;
  flex-direction: column;
  gap: 24rpx;
}

/* ── PROFILE & TSB CARD ── */
.profile-card {
  background-color: #151518;
  border: 1rpx solid rgba(255, 255, 255, 0.08);
  border-radius: 28rpx;
  padding: 28rpx;
  margin-bottom: 24rpx;
}

.profile-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20rpx;
}

.profile-name {
  font-size: 32rpx;
  font-weight: 900;
  color: #ffffff;
  display: block;
}

.profile-meta {
  font-size: 22rpx;
  color: #8e8e93;
  margin-top: 4rpx;
  display: block;
}

.tsb-badge {
  padding: 6rpx 18rpx;
  border-radius: 24rpx;
  border: 1rpx solid transparent;
}

.tsb-badge-text {
  font-size: 20rpx;
  font-weight: bold;
}

.tsb-fresh {
  background-color: rgba(48, 209, 88, 0.15);
  border-color: rgba(48, 209, 88, 0.3);
  color: #30d158;
}

.tsb-neutral {
  background-color: rgba(100, 210, 255, 0.15);
  border-color: rgba(100, 210, 255, 0.3);
  color: #64d2ff;
}

.tsb-optimal {
  background-color: rgba(175, 82, 222, 0.15);
  border-color: rgba(175, 82, 222, 0.3);
  color: #d084f7;
}

.tsb-fatigued {
  background-color: rgba(255, 159, 10, 0.15);
  border-color: rgba(255, 159, 10, 0.3);
  color: #ff9f0a;
}

.tsb-danger {
  background-color: rgba(255, 69, 58, 0.15);
  border-color: rgba(255, 69, 58, 0.3);
  color: #ff453a;
}

.tsb-grid {
  display: flex;
  gap: 16rpx;
  padding-top: 16rpx;
  border-top: 1rpx solid rgba(255, 255, 255, 0.05);
}

.tsb-item {
  flex: 1;
  background-color: #1a1a1e;
  border-radius: 18rpx;
  padding: 16rpx 12rpx;
  text-align: center;
}

.tsb-label {
  font-size: 20rpx;
  color: #8e8e93;
  display: block;
  margin-bottom: 4rpx;
}

.tsb-val {
  font-size: 28rpx;
  font-weight: 900;
  display: block;
}

.text-cyan { color: #64d2ff; }
.text-amber { color: #ff9f0a; }
.text-green { color: #30d158; }
.text-purple { color: #bf5af2; }

.risk-box {
  margin-top: 18rpx;
  background-color: rgba(255, 69, 58, 0.1);
  border: 1rpx solid rgba(255, 69, 58, 0.25);
  border-radius: 18rpx;
  padding: 16rpx;
  display: flex;
  align-items: flex-start;
  gap: 12rpx;
}

.risk-icon {
  font-size: 24rpx;
}

.risk-text {
  font-size: 22rpx;
  color: #ffb4ab;
  line-height: 1.4;
  flex: 1;
}

/* ── RACE SETUP CARD ── */
.race-setup-card {
  background-color: #151518;
  border: 1rpx solid rgba(255, 255, 255, 0.08);
  border-radius: 28rpx;
  padding: 28rpx;
  margin-bottom: 24rpx;
}

.presets-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12rpx;
  margin-bottom: 18rpx;
}

.preset-chip {
  background-color: #1a1a1e;
  border: 1rpx solid rgba(255, 255, 255, 0.06);
  padding: 8rpx 20rpx;
  border-radius: 20rpx;
}

.preset-chip.active {
  background-color: rgba(175, 82, 222, 0.25);
  border-color: #af52de;
}

.chip-text {
  font-size: 22rpx;
  color: #c7c7cc;
}

.preset-chip.active .chip-text {
  color: #ffffff;
  font-weight: bold;
}

.inputs-row {
  display: flex;
  gap: 16rpx;
}

.input-col {
  display: flex;
  flex-direction: column;
  gap: 8rpx;
}

.flex-2 { flex: 2; }
.flex-1 { flex: 1; }

.input-label {
  font-size: 20rpx;
  color: #8e8e93;
}

.setup-input {
  background-color: #1a1a1e;
  border: 1rpx solid rgba(255, 255, 255, 0.1);
  border-radius: 16rpx;
  height: 64rpx;
  padding: 0 16rpx;
  font-size: 24rpx;
  color: #ffffff;
}

/* ── ZONES LIST ── */
.zones-list {
  display: flex;
  flex-direction: column;
  gap: 14rpx;
}

.zone-item {
  background-color: #1a1a1e;
  border-radius: 18rpx;
  padding: 18rpx;
}

.zone-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 6rpx;
}

.zone-name {
  font-size: 24rpx;
  font-weight: bold;
  color: #e5e5ea;
}

.zone-range {
  font-size: 24rpx;
  font-weight: 900;
  color: #d084f7;
}

.zone-desc {
  font-size: 20rpx;
  color: #8e8e93;
  line-height: 1.4;
}

.hero-card {
  background: linear-gradient(135deg, rgba(175, 82, 222, 0.2) 0%, #151518 100%);
  border: 1rpx solid rgba(175, 82, 222, 0.3);
  border-radius: 28rpx;
  padding: 32rpx;
  box-shadow: 0 10rpx 30rpx rgba(0, 0, 0, 0.5);
}

.phase-badge {
  display: inline-flex;
  align-items: center;
  gap: 8rpx;
  background-color: rgba(175, 82, 222, 0.2);
  border: 1rpx solid rgba(175, 82, 222, 0.3);
  padding: 6rpx 18rpx;
  border-radius: 20rpx;
  margin-bottom: 20rpx;
}

.sparkle {
  font-size: 20rpx;
}

.phase-text {
  font-size: 22rpx;
  font-weight: bold;
  color: #d084f7;
}

.summary-title {
  font-size: 32rpx;
  font-weight: bold;
  color: #ffffff;
  line-height: 1.4;
  margin-bottom: 16rpx;
  display: block;
}

.fitness-detail {
  font-size: 24rpx;
  color: #c7c7cc;
  line-height: 1.6;
  display: block;
}

.section-card {
  background-color: #151518;
  border: 1rpx solid rgba(255, 255, 255, 0.06);
  border-radius: 28rpx;
  padding: 28rpx;
}

.card-title-row {
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 18rpx;
}

.section-icon {
  font-size: 28rpx;
}

.card-title {
  font-size: 28rpx;
  font-weight: bold;
  color: #ffffff;
}

.workout-box {
  background-color: rgba(175, 82, 222, 0.1);
  border: 1rpx solid rgba(175, 82, 222, 0.2);
  border-radius: 20rpx;
  padding: 22rpx;
}

.workout-text {
  font-size: 26rpx;
  color: #e5c9f9;
  line-height: 1.5;
}

.recovery-box {
  background-color: rgba(48, 209, 88, 0.1);
  border: 1rpx solid rgba(48, 209, 88, 0.2);
  border-radius: 20rpx;
  padding: 22rpx;
}

.recovery-text {
  font-size: 26rpx;
  color: #bdf2cc;
  line-height: 1.5;
}

.tip-footnote {
  font-size: 20rpx;
  color: #636366;
  margin-top: 14rpx;
  display: block;
}

.suggestions-list {
  display: flex;
  flex-direction: column;
  gap: 14rpx;
}

.sugg-item {
  background-color: #1a1a1e;
  border-radius: 18rpx;
  padding: 20rpx;
}

.sugg-badge {
  font-size: 20rpx;
  font-weight: bold;
  color: #bf5af2;
  margin-bottom: 8rpx;
  display: block;
}

.sugg-text {
  font-size: 24rpx;
  color: #e5e5ea;
  line-height: 1.5;
}

.empty-card {
  background-color: #151518;
  border-radius: 28rpx;
  padding: 60rpx 40rpx;
  text-align: center;
}

.empty-icon {
  font-size: 60rpx;
  margin-bottom: 20rpx;
  display: block;
}

.empty-title {
  font-size: 32rpx;
  font-weight: bold;
  color: #ffffff;
  margin-bottom: 12rpx;
  display: block;
}

.empty-desc {
  font-size: 24rpx;
  color: #8e8e93;
  line-height: 1.5;
  margin-bottom: 30rpx;
  display: block;
}

.primary-btn {
  background-color: #af52de;
  color: #ffffff;
  font-size: 28rpx;
  font-weight: bold;
  border-radius: 24rpx;
  height: 80rpx;
  line-height: 80rpx;
}
</style>
